### ISSUE TITLE
Ability to not sort inventory (just chests) / sorting issues

### ISSUE THREAD

**Issue by flipperbw** [mcglonelevi/RaftModSortInventory#1]
It'd be nice to be able to just sort the chests, since I usually have my own inventory pretty spaced out and it's a bit annoying to redo that every time.

Additionally, there seems to be a strange issue where sorting multiple times will randomly shuffle items, or put them in a strange order (5 batteries in a row, then a bunch of stuff, then another battery at the end). I think some sort of categorization would be nice, like utilities first, then tools, etc.

**Comment by mcglonelevi** [comment]
Hey flipperbw,

I had no idea anyone was using this Raft mod.  I released this a while back, and I have not updated it since.  I am sure that there have been bugs introduced from the recent changes to Raft.  I can take a look, but getting a fix out might take a while.

Would you be interested in submitting a PR or becoming a contributor/maintainer?  If not, that's fine.

**Comment by mcglonelevi** [comment]
I did look into your issue, and I found the following:

1. The way Raft mods are built/installed has changed since I last committed nearly a year ago.
2. I think the battery issue might be due to a sorting issue, because you can pick up a battery after they have been used, which might have unintended consequences for my sorting logic.  I have not had time to confirm, but that is my theory.
3. In terms of categorizing, I don't really play Raft that often anymore, and I don't have time to actively maintain this repo.  Categorizing is pretty subjective, and I am hesitant to add and maintain that feature.

I am running short on time, but I don't think I will be able to actively support this mod.

**Comment by mcglonelevi** [comment]
In case you choose to fork/clone the repo, I added the MIT license so that you are free to do so.

**Comment by flipperbw** [comment]
Thanks. It does still work, but I'm not sure I could take it over right now. I'll look into it more.

**Comment by mcglonelevi** [comment]
It's been a while.  I am going to close this out for now.
